# Generated by Django 6.1 on 2026-08-30 23:24

import django.db.models.deletion
import entregas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_rastreio', models.CharField(editable=False, max_length=20, unique=True)),
                ('cliente_nome', models.CharField(max_length=150)),
                ('cliente_contato', models.CharField(blank=True, max_length=100)),
                ('origem', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('transportadora', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='entregas.empresa')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('COLETADO', 'Coletado'), ('EM_TRANSITO', 'Em trânsito'), ('SAIU_PARA_ENTREGA', 'Saiu para entrega'), ('ENTREGUE', 'Entregue'), ('EXTRAVIADO', 'Extraviado')], max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=entregas.models.foto_upload_path)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='entregas.entrega')),
            ],
            options={
                'verbose_name_plural': 'Status históricos',
                'ordering': ['data_hora'],
            },
        ),
    ]
