# Generated by Django 6.1 on 2026-08-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='prazo_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
